# Generated by Django 5.2.16 on 2026-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('SAT_TUE', 'السبت والثلاثاء'), ('SUN_WED', 'الأحد والأربعاء'), ('SAT', 'السبت'), ('SUN', 'الأحد'), ('MON', 'الاثنين'), ('TUE', 'الثلاثاء'), ('WED', 'الأربعاء'), ('THU', 'الخميس'), ('FRI', 'الجمعة')], max_length=10),
        ),
    ]
