# Generated by Django 5.2.16 on 2026-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='governorate',
            field=models.CharField(blank=True, default='القليوبية', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
